import re
from PyLTSpice import SpiceEditor

def parameterize_netlist(netlist_path, tunable_components):
    """
    Modifies the netlist to use parameters for the specified components.
    Returns the new list of tunable parameter names.
    """
    net = SpiceEditor(netlist_path)
    new_tunable = []
    
    # Read raw content to find .params and component definitions
    with open(netlist_path, 'r', encoding='latin-1') as f:
        content = f.read()

    # Helper to find PULSE
    # Vsw N001 sw PULSE(0 10 0 1n 1n 3.38u 10u)
    
    updates_made = False

    for comp in tunable_components:
        # 1. Get current definition
        # PyLTSpice get_component_value might return the string
        # but for Vsw it might return 'PULSE(...)'
        try:
            val = net.get_component_value(comp)
        except:
            # Fallback for complex lines
            val = ""
            # regex find line starting with comp
            match = re.search(f"^{comp}\s+.*$", content, re.MULTILINE)
            if match:
                val = match.group(0)

        print(f"Processing {comp}, Val: {val}")

        # Case A: PULSE Source (Vsw)
        # Look for PULSE(...)
        if "PULSE" in val:
            # Extract arguments
            # Pattern: PULSE(v1 v2 td tr tf ton per)
            # Remove commas if any
            clean_val = val.replace(',', ' ')
            m = re.search(r"PULSE\((.*?)\)", clean_val)
            if m:
                args = m.group(1).split()
                if len(args) >= 7:
                    # ton is index 5, period is index 6
                    ton = args[5]
                    period = args[6]
                    
                    param_name = f"Ton_{comp}"
                    
                    # Create param
                    net.set_parameter(param_name, ton)
                    
                    # Update component model
                    # Reconstruct string
                    args[5] = f"{{{param_name}}}"
                    new_args = " ".join(args)
                    new_model = f"PULSE({new_args})"
                    
                    net.set_element_model(comp, new_model)
                    new_tunable.append(param_name)
                    updates_made = True
                    print(f"  -> Parameterized Pulse Ton: {param_name}={ton}")
                    continue

        # Case B: Already Parameterized (Cout)
        # Check if value has {Param}
        # Crude check in the raw line or value
        # For Cout: Q={C_min}*x + ({C_nom}-{C_min}) ...
        if "{" in val and "}" in val:
            # Extract variable names
            vars_found = re.findall(r"\{(\w+)\}", val)
            # Heuristic: Filter for variables that are actually defined in .params
            # For now, just add them all? That might be too many.
            # specifically for Cout in this project, we know it's C_nom.
            # Let's verify existing .params
            
            # Simple approach: If 'C_nom' is in there, pick it.
            if 'C_nom' in vars_found:
                 new_tunable.append('C_nom')
                 print(f"  -> Found existing param C_nom in {comp}")
                 continue
            
            # If standard cap with {val}
            if len(vars_found) == 1:
                new_tunable.append(vars_found[0])
                continue

        # Case C: Standard Value (Rload 6, Cin 300u)
        # Create a new parameter
        # Val might be '300u' or '6'
        # Ignore if it's not a simple value (e.g. models)
        if re.match(r"^[0-9\-\+\.a-zA-Z]+$", val):
             param_name = f"val_{comp}"
             net.set_parameter(param_name, val)
             net.set_component_value(comp, f"{{{param_name}}}")
             new_tunable.append(param_name)
             updates_made = True
             print(f"  -> Parameterized Value: {param_name}={val}")
             continue
        
        # Fallback: keep original if we couldn't parameterize
        # new_tunable.append(comp) # Actually, if we keep original, the Agent fails. 
        # But we must populate the list.
        print(f"  -> Could not parameterize {comp}, keeping as is.")
        new_tunable.append(comp)

    if updates_made:
        net.write_netlist(netlist_path)
    
    return new_tunable

# TEST
if __name__ == "__main__":
    import shutil
    # Setup test file
    src = r"c:\Users\david\Desktop\PhD\progetti\SpiceAgent\Circuits\Buck_converter\Buck_converter_real.asc"
    dst = "temp_param_test.net"
    
    # We need to create a netlist from asc first for testing properly, or use existing net
    # let's use the one generated by V3 results if exists
    net_src = r"c:\Users\david\Desktop\PhD\progetti\SpiceAgent\PowerAgent\results_v3\optimized_design.net"
    if os.path.exists(net_src):
        shutil.copy(net_src, dst)
        
        print("Original Tunable: ['Vsw', 'Cout']")
        new_params = parameterize_netlist(dst, ['Vsw', 'Cout'])
        print(f"New Tunable: {new_params}")
        
        with open(dst, 'r') as f:
            print("\n--- Resulting Netlist Fragment ---")
            lines = f.readlines()
            for l in lines:
                if "Vsw" in l or ".param" in l or "Cout" in l:
                    print(l.strip())
